# These are supported funding model platforms

github: [yourusername]
patreon: yourpatreon
open_collective: yourcollective
ko_fi: yourkofi
tidelift: npm/obsidian-ai-assistant
community_bridge: yourproject
liberapay: yourliberapay
issuehunt: yourissuehunt
otechie: yourotechie
custom: ['https://www.buymeacoffee.com/yourname']